import type { Slide } from "@/data/deck/types";
import { GeologicalFigure } from "./Figure";
import { WorkflowDiagram } from "./WorkflowDiagram";
import { WidgetRegistry } from "./widgets/WidgetRegistry";
import { accentBg, accentBorder, accentText } from "./ui";

export function SlideRenderer({ slide, number, total }: { slide: Slide; number: number; total: number }) {
  return <article className="slide-content grain stage-in bg-paper text-ink"><div className="absolute left-0 top-0 h-3 w-full bg-oxy" /><main className="flex h-full flex-col px-24 pb-20 pt-16"><header className={`${slide.figure ? "mb-5" : "mb-8"} shrink-0`}><div className="flex items-center justify-between gap-8"><p className="slide-kicker font-mono text-oxy">{slide.kicker}</p>{slide.activityLabel && <span className="slide-badge rounded-full bg-ochre/15 px-5 py-2 font-mono font-bold text-ochre">{slide.activityLabel}</span>}</div>{slide.layout !== "title" && slide.layout !== "divider" && <h1 className="slide-title mt-4 max-w-[1500px] font-slab font-semibold">{slide.title}</h1>}{slide.lead && slide.layout !== "title" && slide.layout !== "divider" && <p className={`slide-body max-w-[1500px] text-inksoft ${slide.figure ? "mt-2" : "mt-4"}`}>{slide.lead}</p>}</header><div className="min-h-0 flex-1">{renderLayout(slide)}</div>{(slide.takeaway || slide.note) && <footer className={`slide-footer mt-6 shrink-0 border-l-8 px-5 py-3 ${slide.takeaway ? "border-oxy bg-oxy/10" : "border-ochre bg-ochre/10"}`}><strong className="mr-3 font-mono uppercase text-oxy">{slide.takeaway ? "Takeaway" : "Field note"}</strong><span className="text-inksoft">{slide.takeaway ?? slide.note}</span></footer>}<span className="slide-page absolute bottom-6 right-8 font-mono text-inksoft">{String(number).padStart(2,"0")} / {total}</span></main></article>;
}

function renderLayout(slide: Slide) {
  if (slide.layout === "title") return <div className="flex h-full flex-col justify-center"><h1 className="slide-title-lg max-w-[1450px] font-slab font-semibold text-ink">{slide.title}</h1><p className="slide-body-lg mt-8 max-w-[1220px] text-inksoft">{slide.lead}</p><div className="mt-12 flex gap-5">{slide.stats?.map((s) => <div key={s.label} className="min-w-52 border-t-4 border-oxy pt-4"><strong className="font-disp text-6xl">{s.value}</strong><span className="slide-caption ml-3 text-inksoft">{s.label}</span></div>)}</div></div>;
  if (slide.layout === "divider") return <div className="grid h-full grid-cols-[1.2fr_.8fr] items-center gap-20"><div><h1 className="slide-title-lg font-slab font-semibold">{slide.title}</h1><p className="slide-body-lg mt-8 text-inksoft">{slide.lead}</p></div><div className="border-l border-line pl-12"><p className="slide-kicker font-mono text-oxy">By the end</p><ol className="mt-6 space-y-7">{slide.objectives?.map((o,i) => <li key={o} className="slide-body flex gap-5"><span className="font-mono text-ochre">0{i+1}</span>{o}</li>)}</ol></div></div>;
  if (slide.layout === "widget") return <div className="deck-widget"><WidgetRegistry slide={slide} /></div>;
  if (slide.layout === "diagram") return <WorkflowDiagram diagram={slide.diagram} />;
  if (slide.layout === "quote") return <div className="flex h-full items-center"><blockquote className="max-w-[1600px]"><span className="font-slab text-[150px] leading-none text-ochre">“</span><p className="slide-subtitle -mt-14 font-slab leading-tight">{slide.quote}</p>{slide.attribution && <cite className="slide-caption mt-8 block not-italic text-inksoft">— {slide.attribution}</cite>}</blockquote></div>;
  if (slide.layout === "table" && slide.table) return <div className="overflow-hidden rounded-lg border border-line bg-card"><table className="w-full table-fixed"><thead className="bg-ink text-card"><tr>{slide.table.head.map((h) => <th key={h} className="slide-chrome px-5 py-4 text-left font-mono uppercase">{h}</th>)}</tr></thead><tbody>{slide.table.rows.map((row,ri) => <tr key={ri} className="border-t border-line even:bg-paper/70">{row.map((cell,ci) => <td key={ci} className={`px-5 py-3 align-top ${ci === 0 ? "slide-caption font-semibold text-ink" : "slide-chrome text-inksoft"}`}>{cell}</td>)}</tr>)}</tbody></table></div>;
  if (slide.layout === "cards") return <div className="grid grid-cols-2 gap-5">{slide.cards?.map((card,i) => { const a = card.accent ?? "oxy"; return <section key={card.title} className={`min-h-56 rounded-lg border-l-8 bg-card p-6 ring-1 ring-line ${accentBorder[a]}`}><span className={`slide-chrome font-mono uppercase ${accentText[a]}`}>{card.tag ?? `0${i+1}`}</span><h2 className="slide-body-lg mt-3 font-slab font-semibold">{card.title}</h2><p className="slide-caption mt-3 text-inksoft">{card.text}</p></section>})}</div>;
  if (slide.layout === "steps") return <div className="grid grid-cols-3 gap-5">{slide.steps?.map((step,i) => { const a = step.accent ?? "oxy"; return <section key={step.title} className="min-h-48 rounded-lg bg-card p-5 ring-1 ring-line"><div className={`grid size-12 place-items-center rounded-full font-mono text-card ${accentBg[a]}`}>{i+1}</div><h2 className="slide-body mt-4 font-semibold">{step.title}</h2><p className="slide-caption mt-2 text-inksoft">{step.text}</p></section>})}</div>;
  if (slide.layout === "compare" && slide.compare) return <div className="grid grid-cols-2 gap-7"><Compare title={slide.compare.leftTitle} items={slide.compare.left} tone="moss" /><Compare title={slide.compare.rightTitle} items={slide.compare.right} tone="oxy" /></div>;
  if (slide.layout === "split") { const bullets = slide.bullets?.map((b,i) => <section key={`${b.title}-${i}`} className="flex gap-5 rounded-lg bg-card p-5 ring-1 ring-line"><span className="slide-chrome font-mono font-bold text-oxy">{b.label ?? `0${i+1}`}</span><div><h2 className="slide-body font-semibold">{b.title}</h2><p className="slide-caption mt-1 text-inksoft">{b.text}</p></div></section>); const stats = slide.stats && <div className="grid grid-cols-3 gap-4">{slide.stats.map((s) => <div key={s.label} className="border-t-4 border-ochre pt-3"><strong className="font-disp text-4xl">{s.value}</strong><p className="slide-chrome text-inksoft">{s.label}</p></div>)}</div>;
    if (!slide.figure) return <div className="flex h-full flex-col gap-5"><div className="grid grid-cols-2 content-start gap-5">{bullets}</div>{stats}</div>;
    return <div className="grid gap-8 grid-cols-[.9fr_1.1fr]"><div className="space-y-4">{bullets}{stats}</div><GeologicalFigure figure={slide.figure} /></div>; }

  return null;
}

function Compare({ title, items, tone }: { title: string; items: string[]; tone: "moss" | "oxy" }) { return <section className={`rounded-lg border-t-8 bg-card p-7 ${tone === "moss" ? "border-moss" : "border-oxy"}`}><h2 className="slide-body-lg font-slab font-semibold">{title}</h2><ul className="mt-5 space-y-5">{items.map((item,i) => <li key={i} className="slide-caption flex gap-4 text-inksoft"><span className={tone === "moss" ? "text-moss" : "text-oxy"}>●</span>{item}</li>)}</ul></section> }